'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let meta,registry={},poolResult=null,poolRequest=null,job=null,pollTimer=null,poolGeneration=0;
const fmt=(v,n=2)=>v===null||v===undefined?'—':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:n,minimumFractionDigits:n});
const pct=v=>v===null||v===undefined?'—':fmt(v*100)+'%';
function page(id){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===id));document.querySelectorAll('.tabs button').forEach(e=>{e.classList.toggle('active',e.dataset.page===id);if(e.dataset.page===id)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current');});refreshContexts();window.scrollTo(0,0);requestAnimationFrame(()=>window.ResearchCharts?.resizeVisible());}
function error(e){$('global-error').hidden=false;$('global-error').textContent=e.message||String(e);}
async function api(url,data){const g=poolGeneration;const j=await window.OfflineData.api(url,data);if(url==='/api/pool'&&g!==poolGeneration)throw new Error('参数已改变，请重新查询');return j;}
async function action(target,fn){$(target).innerHTML='<div class="busy" role="status">正在加载或筛选，请稍候…</div>';$('global-error').hidden=true;try{await fn();}catch(e){$(target).innerHTML='<div class="error" role="alert">'+esc(e.message)+'</div>';}}
function options(el,items,value){$(el).innerHTML=items.map(x=>typeof x==='string'?`<option value="${esc(x)}">${esc(x)}</option>`:`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('');if(value!==undefined)$(el).value=value;}
function settings(){return {start:$('start-quarter').value,end:$('end-quarter').value,cost_bps:Number($('cost-bps').value)};}
function step(id,q,value=1){return registry[id].kind==='rank'?{id,q:Number(q)}:{id,value:Number(value)};}
function singleSteps(){return [step($('single-factor').value,$('single-q').value,$('single-cond').value)];}
function crossSteps(){return [step($('cross-a').value,$('cross-qa').value),step($('cross-b').value,$('cross-qb').value)];}
function labSteps(){return [...$('lab-steps').children].filter(e=>e.querySelector('input').checked).map(e=>step(e.dataset.id,e.querySelector('select').value,e.querySelector('select').value));}
function refreshContexts(){if(!meta||!$('lab-steps').children.length)return;const steps=labSteps();$('pool-rules').textContent='当前筛选：'+(steps.length?steps.map(s=>registry[s.id].name+' '+(s.q?s.q+'%':s.value===1?'满足':'已知不满足')).join(' → '):'全部股票（未启用因子）');const s=settings();$('reverse-settings').textContent=`研究信号区间：${s.start}—${s.end} · 单边综合费用 ${s.cost_bps}bp · 与因子实验室共用设置`;}
function markStale(){refreshContexts();poolGeneration++;poolResult=null;poolRequest=null;$('export-csv').disabled=true;$('export-xlsx').disabled=true;$('pool-note').textContent='参数已变化，请重新查询股票池或比较两期后再导出。';}
function sendLab(steps){const box=$('lab-steps');for(const e of [...box.children])e.querySelector('input').checked=false;for(const s of [...steps].reverse()){const e=box.querySelector(`[data-id="${s.id}"]`);e.querySelector('input').checked=true;e.querySelector('select').value=s.q??s.value;box.prepend(e);}markStale();page('lab');}
function factorValue(r,f){const v=r[f.field];if(v===null||v===undefined)return '—';if(f.unit==='bool')return v===1?'满足':'不满足';if(f.unit==='ratio')return pct(v);return fmt(v)+(f.unit==='%'?'%':f.unit==='倍'?' 倍':'');}
function table(target,rows,columns,{search=false,pageSize=100}={}){
 const host=$(target);let key=null,dir=1,query='',p=0;
 function draw(){let rr=rows.filter(r=>!query||Object.values(r).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase())));if(key)rr.sort((a,b)=>{let x=a[key],y=b[key];if(x==null&&y==null)return String(a.wind_code??'').localeCompare(String(b.wind_code??''));if(x==null)return 1;if(y==null)return -1;return (typeof x==='number'?x-y:String(x).localeCompare(String(y)))*dir||String(a.wind_code??'').localeCompare(String(b.wind_code??''));});p=Math.min(p,Math.max(0,Math.ceil(rr.length/pageSize)-1));const slice=rr.slice(p*pageSize,(p+1)*pageSize);
 host.innerHTML=`<div class="table-toolbar">${search?'<input class="filter" aria-label="搜索股票" placeholder="搜索股票代码 / 公司 / 行业" value="'+esc(query)+'">':''}<span>共 ${rr.length.toLocaleString()} 条 · ${rr.length?p*pageSize+1:0}–${Math.min((p+1)*pageSize,rr.length)}</span><span><button class="prev" ${p===0?'disabled':''}>上一页</button> <button class="next" ${(p+1)*pageSize>=rr.length?'disabled':''}>下一页</button></span></div><div class="table-wrap"><table><thead><tr>${columns.map((c,i)=>`<th><button data-sort="${i}">${esc(c.label)} ${key===c.key?(dir===1?'↑':'↓'):'↕'}</button></th>`).join('')}</tr></thead><tbody>${slice.length?slice.map((r,i)=>'<tr>'+columns.map(c=>'<td class="'+(c.text?'text':'')+'">'+(c.render?c.render(r):esc(r[c.key]??'—'))+'</td>').join('')+'</tr>').join(''):`<tr><td colspan="${columns.length}" class="text">没有符合条件的记录，请放宽筛选或更换季度。</td></tr>`}</tbody></table></div>`;
 host.querySelectorAll('[data-sort]').forEach(e=>e.onclick=()=>{const k=columns[Number(e.dataset.sort)].key;dir=key===k?-dir:1;key=k;draw();});host.querySelector('.prev').onclick=()=>{p--;draw();};host.querySelector('.next').onclick=()=>{p++;draw();};const input=host.querySelector('.filter');if(input)input.oninput=()=>{query=input.value;p=0;const caret=input.selectionStart;draw();const next=host.querySelector('.filter');next.focus();next.setSelectionRange(caret,caret);};host.querySelectorAll('[data-trace]').forEach(e=>e.onclick=()=>trace(e.dataset.trace,e.dataset.quarter));
 }draw();
}
function stockTable(id,rows){table(id,rows,[{key:'wind_code',label:'代码',text:true,render:r=>`<button class="link" data-trace="${esc(r.wind_code)}" data-quarter="${esc(r.quarter)}">${esc(r.wind_code)}</button>`},{key:'stock_name',label:'公司',text:true},{key:'quarter',label:'信号季度'},{key:'industry_current',label:'当前行业',text:true},...meta.factors.map(f=>({key:f.field,label:f.id.toUpperCase()+' '+f.name,render:r=>factorValue(r,f)}))],{search:true});}
async function trace(code,quarter){$('trace-content').textContent='正在读取…';$('trace-dialog').showModal();try{$('trace-content').textContent=JSON.stringify(await api(`/api/trace?code=${encodeURIComponent(code)}&quarter=${encodeURIComponent(quarter)}`),null,2);}catch(e){$('trace-content').textContent=e.message;}}

function downloadText(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function renderBacktest(id,result){const h=$(id),m=result.metrics;h.innerHTML=`<h2>回测结果</h2><p class="muted">${esc(result.start)} 至 ${esc(result.end)} · ${esc(result.market.label)} · 单边费用 ${result.cost_bps}bp</p><div class="metric-strip">${[['年化价格收益',pct(m.annual_return)],['年化超额收益',pct(m.excess_annual_return)],['Sharpe',fmt(m.sharpe)],['最大回撤',pct(m.max_drawdown)]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div><div id="${id}-chart" class="nav-chart-panel"></div><h3>牛市、熊市、震荡市表现</h3><div id="${id}-regimes"></div><h3>逐段市场区间表现</h3><div id="${id}-periods"></div><p class="muted">年化波动 ${pct(m.volatility)} · 平均年内最大回撤 ${pct(m.annual_mdd_mean)}。${esc(result.note)}</p><button class="download-result">下载已发布结果JSON</button><h3>年度表现</h3><div id="${id}-years"></div><h3>季度持仓与现金</h3><div id="${id}-holdings"></div>`;h.querySelector('.download-result').onclick=()=>downloadText('backtest-result.json',JSON.stringify(result,null,2));table(id+'-years',m.years,[{key:'year',label:'年份'},{key:'return_rate',label:'价格收益',render:r=>pct(r.return_rate)},{key:'benchmark_return',label:'基准收益',render:r=>pct(r.benchmark_return)},{key:'excess_return',label:'超额',render:r=>pct(r.excess_return)},{key:'max_drawdown',label:'年内最大回撤',render:r=>pct(r.max_drawdown)},{key:'days',label:'交易天数'}]);table(id+'-holdings',result.holdings,[{key:'quarter',label:'信号季度'},{key:'signal_date',label:'信号日'},{key:'execution_date',label:'执行日'},{key:'selected',label:'目标股票数'},{key:'held',label:'执行后持股数'},{key:'pool_ratio',label:'股票池占比',render:r=>pct(r.pool_ratio)},{key:'cash_weight',label:'执行后现金占比',render:r=>pct(r.cash_weight)}]);renderRegimeAnalysis(id,result);window.ResearchCharts.mount($(id+'-chart'),result).catch(error);}
function renderRegimeAnalysis(id,result){
 const a=result.regime_analysis;if(!a){$(id+'-regimes').textContent='暂无经过核验的市场状态数据。';return;}
 const labels=r=>'<span class="regime-pill '+(r.regime==='牛市'?'bull':r.regime==='熊市'?'bear':'sideways')+'">'+esc(r.regime)+'</span>';
 table(id+'-regimes',a.metrics,[{key:'regime',label:'市场状态',render:labels},{key:'days',label:'交易日数'},{key:'annual_return',label:'年化价格收益',render:r=>pct(r.annual_return)},{key:'excess_annual_return',label:'年化收益差',render:r=>pct(r.excess_annual_return)},{key:'volatility',label:'年化波动',render:r=>pct(r.volatility)},{key:'sharpe',label:'Sharpe',render:r=>fmt(r.sharpe)},{key:'annual_mdd_mean',label:'平均年内条件最大回撤',render:r=>pct(r.annual_mdd_mean)}]);
 $(id+'-regimes').insertAdjacentHTML('afterbegin','<p class="muted">'+esc(a.note)+'</p>');
 table(id+'-periods',a.periods,[{key:'regime',label:'状态',render:labels},{key:'source_start',label:'原区间起点'},{key:'source_end',label:'原区间终点'},{key:'start',label:'实际样本起点'},{key:'end',label:'实际样本终点'},{key:'days',label:'交易日数'},{key:'total_return',label:'区间策略收益',render:r=>pct(r.total_return)},{key:'benchmark_total_return',label:'区间基准收益',render:r=>pct(r.benchmark_total_return)},{key:'max_drawdown',label:'区间最大回撤',render:r=>pct(r.max_drawdown)}]);
}
function backtest(id,steps){return action(id,async()=>{const result=await api('/api/backtest',{...settings(),steps});renderBacktest(id,result);const q=result.valuation_quality;$(id).insertAdjacentHTML('afterbegin',`<div class="notice">本次规则：${steps.length?steps.map(s=>esc(registry[s.id].name)+' '+(s.q?s.q+'%':s.value===1?'满足':'已知不满足')).join(' → '):'全部股票（未启用因子）'}<br>缺报价沿用估值：最高仓位 ${pct(q.max_stale_weight)}，平均仓位 ${pct(q.mean_stale_weight)}，涉及 ${q.days_with_stale} 个交易日。此部分为冻结估值，不代表当日可成交。</div>`);});}
async function pool(compare){markStale();await action('pool-table',async()=>{const req={quarter:$('pool-quarter').value,steps:labSteps(),compare,early:$('compare-quarter').value,late:$('pool-quarter').value};const result=await api('/api/pool',req);poolResult=result;poolRequest=structuredClone(req);$('export-csv').disabled=false;$('export-xlsx').disabled=false;const latest=compare?result.late:result;$('pool-note').textContent=`信号季度 ${latest.quarter} · 观察日 ${latest.signal_date} · 入选 ${latest.count} / ${latest.total} 只 · 参数和导出已绑定本次结果`;table('pool-funnel',latest.funnel,[{key:'name',label:'筛选步骤',text:true},{key:'before',label:'筛选前'},{key:'valid',label:'有效值'},{key:'missing',label:'缺失排除'},{key:'selected',label:'筛选后'}]);$('pool-compare-tabs').innerHTML='';if(compare){for(const [label,rows] of [[`较早 ${result.early.count}`,result.early.rows],[`较晚 ${result.late.count}`,result.late.rows],[`新进 ${result.added.length}`,result.added],[`退出 ${result.removed.length}`,result.removed],[`留存 ${result.retained.length}`,result.retained]]){const btn=document.createElement('button');btn.textContent=label;btn.onclick=()=>stockTable('pool-table',rows);$('pool-compare-tabs').append(btn);}}stockTable('pool-table',latest.rows);});}
async function exportPool(format){if(poolResult)window.OfflineData.exportPool(poolResult,format);}
function showSearch(j){$('search-status').textContent=`${j.status==='running'?'搜索进行中':j.status==='completed'?'搜索完成':j.status==='stopped'?'已停止':'搜索失败'} · 已评估 ${j.evaluated}/${j.budget} · ${j.elapsed} 秒 · 数据原因拒绝 ${j.errors} 项 · 训练 ${j.split.training.join('—')} · 验证 ${j.split.validation.join('—')}。${j.error||''} ${j.coverage}`;$('search-stop').disabled=j.status!=='running';$('search-run').disabled=j.status==='running';if(j.status!=='running'){const out=$('search-results');out.innerHTML='';if(j.error_examples.length){const p=document.createElement('p');p.className='muted';p.textContent='部分候选未通过数据检查：'+j.error_examples.join('；');out.append(p);}if(!j.results.length){out.insertAdjacentHTML('beforeend','<p class="empty">没有满足约束且数据完整的候选。可放宽约束、调整区间后重新搜索。</p>');return;}j.results.forEach((r,i)=>{const card=document.createElement('div');card.className='card';card.innerHTML=`<h3>${i+1}. ${r.steps.map(s=>esc(registry[s.id].name)+(s.q?' '+s.q+'%':' 满足')).join(' → ')}</h3><p>训练年化 ${pct(r.training.annual_return)} · 验证年化 ${pct(r.validation?.annual_return)} · 全样本年化 ${pct(r.full?.annual_return)}</p><p class="muted">训练Sharpe ${fmt(r.training.sharpe)} · 验证Sharpe ${fmt(r.validation?.sharpe)} · 训练最大回撤 ${pct(r.training.max_drawdown)} · 验证最大回撤 ${pct(r.validation?.max_drawdown)}</p><p class="muted">${esc(r.validation_error||r.full_error||'')}</p><button class="apply">送入实验室</button> <button class="details">下载候选结果</button>`;card.querySelector('.apply').onclick=()=>{sendLab(r.steps);$('lab-steps').scrollIntoView({block:'center'});};card.querySelector('.details').onclick=()=>downloadText('candidate.json',JSON.stringify(r,null,2));out.append(card);});}}
async function poll(){if(!job)return;try{const j=await api('/api/job?id='+encodeURIComponent(job));showSearch(j);if(j.status==='running')pollTimer=setTimeout(poll,2000);}catch(e){error(e);$('search-run').disabled=false;}}
async function search(){try{const nullable=id=>$(id).value===''?null:Number($(id).value)/100;const config={objective:$('search-objective').value,factors:[...$('search-factors').querySelectorAll('input:checked')].map(e=>e.value),max_depth:Number($('search-depth').value),budget:Number($('search-budget').value),seconds:Number($('search-seconds').value),top_n:Number($('search-top').value),min_holdings:Number($('search-min').value),max_holdings:Number($('search-max').value),min_nonempty_ratio:Number($('search-nonempty').value),min_annual_return:nullable('search-return'),max_drawdown:nullable('search-dd'),min_pool_ratio:Number($('search-ratio-min').value)/100,max_pool_ratio:Number($('search-ratio-max').value)/100};$('search-run').disabled=true;const j=await api('/api/search',{...settings(),config});job=j.id;showSearch(j);pollTimer=setTimeout(poll,1000);}catch(e){$('search-status').textContent=e.message;$('search-run').disabled=false;}}
async function boot(){meta=await api('/api/summary');registry=Object.fromEntries(meta.factors.map(f=>[f.id,f]));const qs=meta.quarters,last=qs.at(-1);$('data-date').textContent=`因子 ${qs[0]}—${last} · 在线结果版`;
 $('research-home').onclick=()=>page('overview');
 for(const id of ['single-factor','cross-a','cross-b'])options(id,meta.factors.map(f=>({value:f.id,label:f.id.toUpperCase()+' '+f.name})),id==='cross-b'?'f5':id==='single-factor'?'f4':'f1');
 for(const id of ['single-q','cross-qa','cross-qb'])options(id,meta.grid.map(n=>({value:n,label:n+'%'})),20);
 for(const id of ['start-quarter','end-quarter','pool-quarter','compare-quarter','matrix-quarter'])options(id,qs,id==='start-quarter'?qs[1]:id==='compare-quarter'?qs.at(-2):last);
 $('lab-steps').innerHTML=meta.factors.map(f=>`<div class="step" data-id="${f.id}"><label><input type="checkbox" ${f.id==='f4'?'checked':''}> ${f.id.toUpperCase()} ${esc(f.name)}</label><select aria-label="${esc(f.name)}筛选参数">${f.kind==='rank'?meta.grid.map(n=>`<option value="${n}" ${n===20?'selected':''}>${n}%</option>`).join(''):'<option value="1">满足</option>'+(f.id==='f3'?'<option value="0">不满足</option>':'')}</select><button class="up" aria-label="上移${esc(f.name)}">↑</button><button class="down" aria-label="下移${esc(f.name)}">↓</button></div>`).join('');
 $('lab-steps').querySelectorAll('.up').forEach(b=>b.onclick=()=>{const r=b.parentElement;if(r.previousElementSibling)r.before(r.previousElementSibling);markStale();});$('lab-steps').querySelectorAll('.down').forEach(b=>b.onclick=()=>{const r=b.parentElement;if(r.nextElementSibling)r.after(r.nextElementSibling);markStale();});$('lab-steps').onchange=markStale;
 $('stats').innerHTML=[['股票—季度记录',meta.rows.toLocaleString()],['历史证券',meta.stocks.toLocaleString()],['季度截面',qs.length],['最新截面',meta.coverage.at(-1).count.toLocaleString()+'只']].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');
 $('market-note').innerHTML=meta.market.ready?`<p>行情与基准覆盖：${esc(meta.market.start)} 至 ${esc(meta.market.end)}；完整持有期可用信号：${esc(meta.complete_periods[0])} 至 ${esc(meta.complete_periods.at(-1))}。</p>`+meta.market.limitations.map(x=>'<p>'+esc(x)+'</p>').join(''):'<p>'+esc(meta.market.reason)+'</p>';
 table('factor-definitions',meta.factors,[{key:'id',label:'编号',text:true},{key:'name',label:'因子',text:true},{key:'formula',label:'计算方法',render:r=>'<span>'+esc(r.formula)+'</span>'}],{pageSize:10});table('coverage-table',[...meta.coverage].reverse(),[{key:'quarter',label:'季度'},{key:'count',label:'股票数'},...meta.factors.map(f=>({key:f.id,label:f.id.toUpperCase()+' 有效数'}))]);
 $('regime-method').textContent=`沿用 ${meta.regimes.reference_release} 的正式区间；万得全A月末收盘价，回撤/反弹确认阈值 ${(meta.regimes.parameters.drawdown*100).toFixed(0)}% / ${(meta.regimes.parameters.rebound*100).toFixed(0)}%，最短子段 ${meta.regimes.parameters.min_sub_months} 个月（既有基础区间边界保留）。${meta.regimes.warning}。下表原样保留起止日，区间两端均包含。`;table('regime-intervals',meta.regimes.intervals,[{key:'start',label:'起始日期'},{key:'end',label:'结束日期'},{key:'label',label:'市场状态',text:true}],{pageSize:30});
 options('search-objective',Object.entries(meta.objectives).map(([value,label])=>({value,label})));$('search-factors').innerHTML=meta.factors.map(f=>`<label><input type="checkbox" value="${f.id}" checked> ${esc(f.name)}</label>`).join('');
 document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll('[data-open-page]').forEach(b=>b.onclick=()=>page(b.dataset.openPage));$('settings').onchange=refreshContexts;
 $('single-factor').onchange=singleChange;$('single-run').onclick=()=>backtest('single-result',singleSteps());$('single-pool').onclick=()=>sendLab(singleSteps());$('cross-run').onclick=()=>backtest('cross-result',crossSteps());$('cross-pool').onclick=()=>sendLab(crossSteps());$('lab-run').onclick=()=>backtest('lab-result',labSteps());
 for(const id of ['cross-a','cross-b'])$(id).onchange=()=>{const which=id==='cross-a'?'cross-qa':'cross-qb';$(which).disabled=registry[$(id).value].kind==='condition';};
 $('lab-coverage').onclick=()=>action('lab-counts',async()=>table('lab-counts',await api('/api/coverage',{steps:labSteps()}),[{key:'quarter',label:'季度'},{key:'total',label:'上市股票数'},{key:'count',label:'入选数量'}]));
 $('pool-run').onclick=()=>pool(false);$('compare-run').onclick=()=>pool(true);$('pool-quarter').onchange=markStale;$('compare-quarter').onchange=markStale;$('export-csv').onclick=()=>exportPool('csv');$('export-xlsx').onclick=()=>exportPool('xlsx');
 $('matrix-run').onclick=()=>action('matrix-result',async()=>{const m=await api('/api/matrix',{x:$('cross-a').value,y:$('cross-b').value,quarter:$('matrix-quarter').value});$('matrix-result').innerHTML='<div class="table-wrap"><table><thead><tr><th>先行 / 后行</th>'+m.y.map(y=>'<th>'+y+(y===1?' 条件':'%')+'</th>').join('')+'</tr></thead><tbody>'+m.x.map((x,i)=>'<tr><th>'+x+(x===1?' 条件':'%')+'</th>'+m.cells[i].map((v,j)=>`<td><button data-a="${x}" data-b="${m.y[j]}">${v}</button></td>`).join('')+'</tr>').join('')+'</tbody></table></div>';$('matrix-result').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(registry[$('cross-a').value].kind==='rank')$('cross-qa').value=b.dataset.a;if(registry[$('cross-b').value].kind==='rank')$('cross-qb').value=b.dataset.b;$('cross-run').focus();});});
 $('search-run').onclick=search;$('search-stop').onclick=async()=>{if(job)showSearch(await api('/api/stop',{id:job}));};$('load-code').onclick=()=>action('code-result',async()=>{const code=await api('/api/code');$('code-result').innerHTML=Object.entries(code).map(([name,body])=>`<details><summary>${esc(name)}.py</summary><pre>${esc(body)}</pre></details>`).join('');});singleChange();refreshContexts();document.querySelector('.tabs button.active').setAttribute('aria-current','page');
}
function singleChange(){const f=registry[$('single-factor').value];$('single-q-label').hidden=f.kind!=='rank';$('single-cond-label').hidden=f.kind==='rank';if(f.id==='f7')$('single-cond').value='1';$('single-cond').querySelector('option[value="0"]').disabled=f.id!=='f3';}
boot().then(()=>window.dispatchEvent(new Event('research-ready'))).catch(error);
