import {esc,renderChart,csvData,palette} from './charts.js';
import {mergeSourcePages} from './workspace-sync.js';
import {createHierarchyUI} from './hierarchy.js';
import {createInitialWorkspace} from './initial-workspace.js';
import {createStaticApi} from './static-api.js';
const staticMode=document.documentElement.dataset.mode==='static';
const staticApi=staticMode?createStaticApi():null;
const sourceViewTitle=staticMode?'数据来源':'数据源管理';
const savedMessage=staticMode?'已保存到此浏览器':'已保存到本机';
const connectionMessage=staticMode?'网页快照 · 每 15 秒检查发布更新':'已连接 · 每 15 秒检查更新';
const $=s=>document.querySelector(s),uid=()=>crypto.randomUUID(),types={line:'时序折线',bar:'柱状对比',scatter:'相关散点',seasonal:'年度季节性'};
let catalog={sources:[],indicators:[]},meta=new Map(),values=new Map(),workspace=null,view='dashboard',editedId=null,saveTimer,toastTimer,refreshing=false,renderEpoch=0,saveChain=Promise.resolve(),pendingSave=false;
const statusLabels={ready:'已接入',stale:'更新失败 · 沿用缓存',unmapped:'说明/分类或待映射',needs_mapping:'待映射',empty:'空表'};
const layoutLabels={wide:'纵向时序',horizontal:'横向时序',wide_blocks:'多块时序',long:'长表面板',none:'无连续时序'};
const externalSourceIds=new Set();let polling=false;
const activePage=()=>workspace.pages.find(p=>p.id===workspace.activePageId)||workspace.pages[0];
const activeCard=id=>activePage()?.cards.find(c=>c.id===id);
async function api(path,method='GET',data){if(staticApi)return staticApi(path,method,data);const response=await fetch('/api/'+path,{method,headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});let body;try{body=await response.json();}catch{throw new Error('本地服务未返回有效数据。');}if(!response.ok)throw new Error(body.error||'请求失败');return body;}
function error(message){$('#error-banner').hidden=!message;$('#error-banner').textContent=message||'';}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function save(){pendingSave=true;$('#save-status').textContent='正在保存…';$('#save-status').classList.remove('status-error');clearTimeout(saveTimer);saveTimer=setTimeout(flushSave,450);}
function flushSave(){if(!workspace||!pendingSave)return;pendingSave=false;const snapshot=JSON.stringify(workspace);saveChain=saveChain.catch(()=>{}).then(()=>api('workspace','PUT',JSON.parse(snapshot))).then(()=>{if(!pendingSave){$('#save-status').textContent=savedMessage;$('#save-status').classList.remove('status-error');}}).catch(e=>{$('#save-status').textContent='保存失败 · 请重试';$('#save-status').classList.add('status-error');error(e.message);pendingSave=true;});}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushSave();});window.addEventListener('beforeunload',event=>{if(pendingSave){flushSave();event.preventDefault();event.returnValue='';}});$('#save-status').addEventListener('click',()=>{if(pendingSave)flushSave();});
function setCatalog(next){if(workspace&&!staticMode){const known=new Set(catalog.sources.map(s=>s.id));for(const source of next.sources)if(!known.has(source.id))externalSourceIds.add(source.id);}catalog=next;meta=new Map(catalog.indicators.map(i=>[i.id,i]));$('#connection').textContent=connectionMessage;$('#source-count').textContent=catalog.sources.length;$('#version').textContent='数据版本 '+String(catalog.version||'').slice(0,10);const sourceErrors=catalog.sources.filter(s=>s.error).map(s=>s.name+'：'+s.error);$('#data-warning').hidden=!sourceErrors.length;$('#data-warning').textContent=sourceErrors.join('；');}
const setting=id=>({indicatorId:id,axis:'left',transform:'raw',frequency:'native',aggregation:'mean'});
const card=(title,type,ids=[])=>{const result={id:uid(),title,type,width:'half',start:'',end:'',years:5,reverseX:false,reverseLeft:false,reverseRight:false,series:ids.filter(Boolean).map(setting)};if(['line','bar'].includes(type)&&result.series.length>1){const first=meta.get(result.series[0].indicatorId);for(const series of result.series.slice(1)){const next=meta.get(series.indicatorId);if(first&&next&&(first.unit!==next.unit||first.percent!==next.percent))series.axis='right';}}return result;};
const hierarchyUI=createHierarchyUI({element:'#hierarchy',getCatalog:()=>catalog,getPage:activePage,getMeta:()=>meta,getValues:()=>values,api,ensureValues,makeCard:card,onSave:save,onAddCard:c=>{activePage().cards.push(c);save();render();},toast});
function defaults(){return createInitialWorkspace(catalog,{makeId:uid,makeCard:card});}

function nav(){const current=activePage();$('#pages').innerHTML=workspace.pages.map(p=>`<button class="nav-button ${view==='dashboard'&&p.id===current?.id?'active':''}" data-page="${esc(p.id)}"><span>▦</span><span>${esc(p.name)}</span><span class="count">${p.cards.length}</span></button>`).join('');$('#sources-nav').classList.toggle('active',view==='sources');}
function dateDisplay(value){if(!value)return'尚未更新';const d=new Date(value);return Number.isNaN(+d)?value:d.toLocaleString('zh-CN',{hour12:false});}
function summary(){const ids=new Set(activePage()?.cards.flatMap(c=>c.series.map(s=>s.indicatorId))),selected=[...ids].map(id=>meta.get(id)).filter(Boolean),latest=selected.map(i=>i.end).sort().at(-1)||catalog.indicators.map(i=>i.end).sort().at(-1)||'—';$('#summary').innerHTML=[[staticMode?'发布数据源':'接入数据源',catalog.sources.length,staticMode?'份已发布快照':'份本地工作簿'],['已识别指标',catalog.indicators.length.toLocaleString(),'条时序'],['当前页面图表',activePage()?.cards.length||0,'张自定义图表'],['最近观测日期',latest,'']].map(([label,value,unit])=>`<div class="stat"><div class="stat-label">${label}<span>↗</span></div><strong${label==='最近观测日期'?' style="font-size:20px"':''}>${esc(value)}<small>${unit}</small></strong></div>`).join('');}
async function ensureValues(cards){const ids=[...new Set(cards.flatMap(c=>c.series.map(s=>s.indicatorId)))].filter(id=>meta.has(id)&&!values.has(id));for(let index=0;index<ids.length;index+=40){const result=await api('series?ids='+encodeURIComponent(ids.slice(index,index+40).join(',')));Object.entries(result.series||{}).forEach(([id,data])=>values.set(id,data));}}
function sourceText(c){const sources=[...new Set(c.series.map(s=>{const m=meta.get(s.indicatorId);return m?.sheet;}))].filter(Boolean);return sources.join(' / ')||'选择指标开始研究';}
function cardMarkup(c,index,total){return `<article class="card ${c.width==='full'?'full':''}" data-card="${esc(c.id)}"><div class="card-header"><div><div class="card-title"><h3>${esc(c.title)}</h3></div><div class="card-subtitle">${types[c.type]||'时序折线'} <span>·</span> ${c.start||'全部历史'}${c.end?' — '+c.end:''}${c.type==='seasonal'?' · 最近 '+c.years+' 年':''}</div></div><div class="card-actions"><button data-action="up" title="上移" aria-label="上移图表" ${index===0?'disabled':''}>↑</button><button data-action="down" title="下移" aria-label="下移图表" ${index===total-1?'disabled':''}>↓</button><button data-action="edit">编辑</button><button data-action="more" title="图表操作" aria-label="图表操作">•••</button></div></div><div class="chart" id="chart-${esc(c.id)}"><div class="loading">正在读取观测值…</div></div><div class="chart-warning" hidden></div><div class="card-footer"><span title="${esc(sourceText(c))}">来源 · ${esc(sourceText(c)).slice(0,80)}</span><span><button data-action="csv">CSV</button><button data-action="png">PNG ↗</button></span></div></article>`;}
async function render(){if(!workspace)return;const epoch=++renderEpoch,p=activePage();nav();$('#cards').hidden=view!=='dashboard';$('#sources').hidden=view!=='sources';$('#summary').hidden=view!=='dashboard';$('#page-more').hidden=view!=='dashboard';$('#add-card').hidden=staticMode&&view==='sources';$('#add-card').textContent=view==='sources'?'＋ 添加数据源':'＋ 添加图表';$('#page-title').textContent=view==='sources'?sourceViewTitle:p.name;$('#crumb').textContent=view==='sources'?sourceViewTitle:p.name;$('#page-meta').textContent=view==='sources'?(staticMode?'查看已发布工作簿快照、指标映射与数据口径':'管理本地工作簿，检查工作表映射与数据质量'):(staticMode?'公开网页快照 · 发布更新 ':'本地 Excel 数据 · 最近更新 ')+dateDisplay(catalog.updatedAt);if(view==='sources'){hierarchyUI.hide();$('#diy-heading').hidden=true;renderSources();return;}hierarchyUI.render();nav();summary();$('#diy-heading').hidden=false;$('#cards').innerHTML=p.cards.length?p.cards.map((c,i)=>cardMarkup(c,i,p.cards.length)).join(''):'<div class="empty card full">这个页面还没有图表。<br>从已有指标创建你的第一张研究图。<button class="primary" data-empty-add>＋ 添加图表</button></div>';try{await ensureValues(p.cards);if(epoch!==renderEpoch)return;for(const c of p.cards){if(epoch!==renderEpoch)return;await drawCard(c);}}catch(e){error(e.message);}}
async function drawCard(c){const node=document.getElementById('chart-'+c.id);if(!node)return;try{const warnings=await renderChart(node,c,meta,values);const warning=node.nextElementSibling;warning.textContent=warnings.join('；');warning.hidden=!warnings.length;}catch(e){node.innerHTML='<div class="empty">图表无法绘制：'+esc(e.message)+'</div>';}}
function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function modal(title,body,onReady){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal').showModal();onReady?.();}
$('#modal-close').onclick=()=>$('#modal').close();
function promptName(title,initial,callback){modal(title,`<form id="name-form"><label class="field">名称<input name="name" value="${esc(initial)}" maxlength="80" required autofocus></label><div class="dialog-actions"><button type="button" data-cancel>取消</button><button class="primary" type="submit">保存</button></div></form>`,()=>{$('[data-cancel]').onclick=()=>$('#modal').close();$('#name-form').onsubmit=e=>{e.preventDefault();const name=e.target.elements.namedItem("name").value.trim();if(!name)return;callback(name);$('#modal').close();};});}
function confirmAction(title,description,callback){modal(title,`<p>${esc(description)}</p><div class="dialog-actions"><button data-cancel autofocus>取消</button><button class="danger" id="confirm-action">确认移除</button></div>`,()=>{$('[data-cancel]').onclick=()=>$('#modal').close();$('#confirm-action').onclick=async()=>{try{await callback();$('#modal').close();}catch(e){error(e.message);$('#modal').close();}};});}
function addPage(){promptName('新建研究页面','新研究页面',name=>{const p={id:uid(),name,cards:[]};workspace.pages.push(p);workspace.activePageId=p.id;view='dashboard';save();render();});}
$('#add-page').onclick=addPage;
$('#pages').onclick=e=>{const button=e.target.closest('[data-page]');if(!button)return;workspace.activePageId=button.dataset.page;view='dashboard';save();render();};
$('#sources-nav').onclick=()=>{view='sources';render();};
$('#page-more').onclick=()=>{modal('页面设置',`<p class="muted">${esc(activePage().name)} · ${activePage().cards.length} 张图表</p><div class="compact-actions"><button id="rename-page">重命名</button><button id="new-page">新建页面</button><button id="export-page">导出页面配置</button><button id="import-page">导入页面配置</button><button class="danger" id="delete-page">删除页面</button></div>`,()=>{$('#rename-page').onclick=()=>{$('#modal').close();promptName('重命名页面',activePage().name,name=>{activePage().name=name;save();render();});};$('#new-page').onclick=()=>{$('#modal').close();addPage();};$('#export-page').onclick=()=>{download(JSON.stringify({schemaVersion:1,page:activePage()},null,2),activePage().name+'.json','application/json');toast('页面配置已导出');};$('#import-page').onclick=()=>$('#import-file').click();$('#delete-page').onclick=()=>{$('#modal').close();confirmAction('删除研究页面','将移除此页及其图表配置，原始 Excel 数据不受影响。',()=>{workspace.pages=workspace.pages.filter(p=>p.id!==activePage().id);if(!workspace.pages.length)workspace.pages.push({id:uid(),name:'我的研究',cards:[]});workspace.activePageId=workspace.pages[0].id;save();render();});};});};
function normalizeImportedPage(input){const p=input.page||input;if(!p||typeof p.name!=='string'||!Array.isArray(p.cards)||p.cards.length>100)throw new Error('配置格式无效，需包含页面名称和图卡列表（最多 100 张）。');return{id:uid(),name:p.name.slice(0,80),...(typeof p.hierarchyId==='string'?{hierarchyId:p.hierarchyId}:{}),...(p.hierarchy&&typeof p.hierarchy.id==='string'&&typeof p.hierarchy.sourceId==='string'?{hierarchy:{id:p.hierarchy.id,sourceId:p.hierarchy.sourceId,rootCode:String(p.hierarchy.rootCode||''),hidden:p.hierarchy.hidden===true,diyInitialized:true,flow:p.hierarchy.flow==='import'?'import':'export',metric:p.hierarchy.metric==='quantity'?'quantity':'amount',month:/^\d{4}-\d{2}$/.test(p.hierarchy.month||'')?p.hierarchy.month:'latest',selectedCode:String(p.hierarchy.selectedCode||''),collapsed:Array.isArray(p.hierarchy.collapsed)?p.hierarchy.collapsed.map(String):[]}}:{}),cards:p.cards.map(c=>{if(!Array.isArray(c.series)||c.series.length>100)throw new Error('图卡指标列表无效。');const clean=card(String(c.title||'导入图表').slice(0,150),Object.hasOwn(types,c.type)?c.type:'line');for(const key of ['start','end'])clean[key]=/^\d{4}-\d{2}-\d{2}$/.test(c[key]||'')?c[key]:'';clean.width=c.width==='full'?'full':'half';clean.years=Math.min(30,Math.max(1,Number(c.years)||5));for(const key of ['reverseX','reverseLeft','reverseRight'])clean[key]=c[key]===true;clean.series=c.series.map(s=>({...setting(String(s.indicatorId)),axis:s.axis==='right'?'right':'left',transform:['raw','log','base100','zscore'].includes(s.transform)?s.transform:'raw',frequency:['native','D','W','M','Q','Y'].includes(s.frequency)?s.frequency:'native',aggregation:['mean','median','min','max','first','last','sum'].includes(s.aggregation)?s.aggregation:'mean',...(typeof s.label==='string'?{label:s.label.slice(0,200)}:{}),...(/^#[a-f0-9]{6}$/i.test(s.color||'')?{color:s.color}:{})}));return clean;})};}
$('#import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5e6)throw new Error('配置文件过大。');const p=normalizeImportedPage(JSON.parse(await file.text()));workspace.pages.push(p);workspace.activePageId=p.id;view='dashboard';$('#modal').close();save();render();toast('页面配置已导入，失效指标会在图表中提示');}catch(ex){error(ex.message);}finally{e.target.value='';}};
function addCard(){if(view==='sources'){addSource();return;}const c=card('新建研究图表','line');activePage().cards.push(c);save();render();openEditor(c.id);}
$('#add-card').onclick=addCard;
$('#cards').onclick=async e=>{if(e.target.closest('[data-empty-add]')){addCard();return;}const action=e.target.closest('[data-action]')?.dataset.action,article=e.target.closest('[data-card]');if(!action||!article)return;const c=activeCard(article.dataset.card),cards=activePage().cards,i=cards.indexOf(c);if(action==='edit'){openEditor(c.id);return;}if(action==='more'){cardMenu(c);return;}if(action==='up'||action==='down'){const j=i+(action==='up'?-1:1);if(j>=0&&j<cards.length)[cards[i],cards[j]]=[cards[j],cards[i]];save();render();return;}try{await ensureValues([c]);if(action==='csv'){download(csvData(c,meta,values),c.title+'.csv','text/csv;charset=utf-8');toast('已导出变换后的序列数据');}else if(action==='png'){const node=document.getElementById('chart-'+c.id);if(!node.data)throw new Error('当前图表没有可导出的有效数据。');const originalTitle=node.layout?.title;await Plotly.relayout(node,{'title.text':c.title,'title.font.size':16,'margin.t':48});try{await Plotly.downloadImage(node,{format:'png',filename:c.title,width:1400,height:780,scale:2});}finally{await drawCard(c);}}}catch(ex){error(ex.message);}};
function cardMenu(c){modal('图表操作',`<p class="muted">${esc(c.title)}</p><div class="compact-actions"><button id="duplicate-card">复制图表</button><button id="width-card">改为${c.width==='full'?'半宽':'全宽'}</button><button id="delete-card" class="danger">删除图表</button></div>`,()=>{$('#duplicate-card').onclick=()=>{const copy=structuredClone(c);copy.id=uid();copy.title+=' · 副本';activePage().cards.splice(activePage().cards.indexOf(c)+1,0,copy);$('#modal').close();save();render();};$('#width-card').onclick=()=>{c.width=c.width==='full'?'half':'full';$('#modal').close();save();render();};$('#delete-card').onclick=()=>{$('#modal').close();confirmAction('删除图表','仅删除此图卡配置，原始 Excel 数据不受影响。',()=>{activePage().cards=activePage().cards.filter(x=>x.id!==c.id);save();render();});};});}
const options=(items,current)=>Object.entries(items).map(([value,label])=>`<option value="${esc(value)}" ${value===current?'selected':''}>${esc(label)}</option>`).join('');
function openEditor(id){editedId=id;editorContent();$('#editor').showModal();}
function editorContent(){const c=activeCard(editedId);if(!c)return;$('#editor-body').innerHTML=`<label class="field">图表标题<input id="edit-title" value="${esc(c.title)}" maxlength="150"></label><div class="row"><label class="field">图表类型<select id="edit-type">${options(types,c.type)}</select></label><label class="field">卡片宽度<select id="edit-width">${options({half:'半宽 · 两列布局',full:'全宽 · 整行展示'},c.width)}</select></label></div><div class="row"><label class="field">起始日期<input type="date" id="edit-start" value="${esc(c.start)}"></label><label class="field">结束日期<input type="date" id="edit-end" value="${esc(c.end)}"></label></div><div class="chips"><button data-range="1">近 1 年</button><button data-range="3">近 3 年</button><button data-range="5">近 5 年</button><button data-range="all">全部历史</button></div><label class="field" id="years-field" ${c.type!=='seasonal'?'hidden':''}>季节性展示年份数<input type="number" min="1" max="30" id="edit-years" value="${c.years||5}"></label><div class="check-row">${[['reverseX','X 轴反向'],['reverseLeft','左轴反向'],['reverseRight','右轴反向']].map(([key,label])=>`<label><input type="checkbox" data-reverse="${key}" ${c[key]?'checked':''}>${label}</label>`).join('')}</div><p class="help">${c.type==='scatter'?'第一个指标为 X，后续指标为 Y；按共同有效日期配对。':'先裁剪日期，再进行频率聚合与数值变换。缺失值保留为空，不补零。'}</p><div class="section-label">已选指标 <span id="selected-count">${c.series.length}</span></div><div id="selected-series"></div><div class="section-label">添加研究指标</div><label class="field">搜索名称、代码或工作表<input id="indicator-search" type="search" placeholder="例如：进口金额、854231"></label><div class="row"><label class="field">数据源<select id="filter-source"><option value="">所有数据源</option>${catalog.sources.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label class="field">工作表<select id="filter-sheet"><option value="">所有工作表</option>${[...new Set(catalog.indicators.map(i=>i.sheet))].map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}</select></label></div><div id="indicator-results" class="muted" style="margin-bottom:8px"></div><div id="indicator-list" class="indicator-list"></div><p class="source-hint">${staticMode?'设置仅保存到此浏览器，不修改公开网站。':'设置自动保存到本机。'}导出 CSV 包含日期裁剪、聚合和变换后的序列。</p>`;renderSelected();renderIndicators();
 for(const key of ['title','type','width','start','end','years'])$('#edit-'+key).onchange=e=>{let value=e.target.value;if(key==='years')value=Math.min(30,Math.max(1,parseInt(value)||5));if((key==='start'&&c.end&&value>c.end)||(key==='end'&&value&&c.start>value)){toast('起始日期不能晚于结束日期');e.target.value=c[key];return;}c[key]=value;save();render();if(key==='type')editorContent();};
 $('#edit-title').oninput=e=>{c.title=e.target.value;const heading=document.getElementById('chart-'+c.id)?.closest('.card')?.querySelector('h3');if(heading)heading.textContent=c.title;save();};
 $('#editor-body').querySelectorAll('[data-reverse]').forEach(el=>el.onchange=()=>{c[el.dataset.reverse]=el.checked;save();drawCard(c);});
 $('#editor-body').querySelectorAll('[data-range]').forEach(el=>el.onclick=()=>{if(el.dataset.range==='all'){c.start='';c.end='';}else{const end=c.series.map(s=>meta.get(s.indicatorId)?.end).filter(Boolean).sort().at(-1)||catalog.indicators.map(i=>i.end).filter(Boolean).sort().at(-1)||new Date().toISOString().slice(0,10);const date=new Date(end+'T00:00:00Z');date.setUTCFullYear(date.getUTCFullYear()-Number(el.dataset.range));c.start=date.toISOString().slice(0,10);c.end=end;}save();render();editorContent();});
 $('#indicator-search').oninput=renderIndicators;$('#filter-source').onchange=()=>{const source=$('#filter-source').value;$('#filter-sheet').innerHTML='<option value="">所有工作表</option>'+[...new Set(catalog.indicators.filter(i=>!source||i.sourceId===source).map(i=>i.sheet))].map(s=>`<option>${esc(s)}</option>`).join('');renderIndicators();};$('#filter-sheet').onchange=renderIndicators;
}
function renderSelected(){const c=activeCard(editedId);if(!c)return;$('#selected-count').textContent=c.series.length;$('#selected-series').innerHTML=c.series.length?c.series.map((s,i)=>{const m=meta.get(s.indicatorId);return `<div class="series-editor" data-series="${i}"><div class="series-top"><strong><span style="color:${s.color||palette[i%palette.length]}">●</span> ${c.type==='scatter'?(i?'Y · ':'X · '):''}${esc(m?.name||'失效指标 · '+s.indicatorId)}</strong><button class="icon" data-remove-series="${i}" aria-label="移除指标">×</button></div><div class="row"><label class="field">坐标轴<select data-setting="axis">${options({left:'左轴',right:'右轴'},s.axis)}</select></label><label class="field">数值变换<select data-setting="transform">${options({raw:'原始值',log:'自然对数',base100:'基期 = 100',zscore:'Z-score'},s.transform)}</select></label></div><div class="row"><label class="field">频率<select data-setting="frequency">${options({native:'原始频率',D:'日频',W:'周频',M:'月频',Q:'季频',Y:'年频'},s.frequency)}</select></label><label class="field">聚合方法<select data-setting="aggregation">${options({mean:'均值',median:'中位数',max:'最大值',min:'最小值',first:'第一条',last:'最后一条',sum:'合计'},s.aggregation)}</select></label></div><div class="source-hint">${esc(m?.unit||'单位未注明')} · ${esc(m?.frequency||'未知频率')} · ${esc(m?.locator||'指标已从目录移除')}<br>${esc(m?.start||'—')} — ${esc(m?.end||'—')} · ${m?.count||0} 条观测 · ${m?.missingCount||0} 个缺失</div></div>`;}).join(''):'<p class="muted">尚未选择指标，在下方搜索并添加。</p>';
 $('#selected-series').querySelectorAll('[data-setting]').forEach(el=>el.onchange=()=>{const i=Number(el.closest('[data-series]').dataset.series);c.series[i][el.dataset.setting]=el.value;save();render();});$('#selected-series').querySelectorAll('[data-remove-series]').forEach(el=>el.onclick=()=>{c.series.splice(Number(el.dataset.removeSeries),1);save();render();renderSelected();renderIndicators();});}
function renderIndicators(){const c=activeCard(editedId);if(!c||!$('#indicator-list'))return;const q=$('#indicator-search').value.trim().toLowerCase(),source=$('#filter-source').value,sheet=$('#filter-sheet').value,items=catalog.indicators.filter(i=>(!source||i.sourceId===source)&&(!sheet||i.sheet===sheet)&&(!q||[i.name,i.code,i.sheet].join(' ').toLowerCase().includes(q)));$('#indicator-results').textContent=`找到 ${items.length} 个指标${items.length>100?' · 显示前 100 项，请细化搜索':''}`;$('#indicator-list').innerHTML=items.slice(0,100).map(i=>`<button class="indicator-option ${c.series.some(s=>s.indicatorId===i.id)?'selected':''}" data-indicator="${esc(i.id)}">${c.series.some(s=>s.indicatorId===i.id)?'✓':'＋'} ${esc(i.name)}<small>${esc(i.sheet)} · ${esc(i.unit||'单位未注明')} · ${esc(i.code||i.frequency||'')} · ${i.count} 条</small></button>`).join('')||'<div class="empty">没有匹配指标</div>';$('#indicator-list').querySelectorAll('[data-indicator]').forEach(el=>el.onclick=async()=>{if(c.series.some(s=>s.indicatorId===el.dataset.indicator)){toast('该指标已添加，可在上方调整');return;}c.series.push(setting(el.dataset.indicator));save();renderSelected();renderIndicators();await render();});}
async function refresh(){if(refreshing)return;refreshing=true;$('#refresh').disabled=true;$('#refresh').textContent='↻ 更新中…';try{const result=await api('refresh','POST',{});setCatalog(result.catalog);if(!staticMode||result.changed)values.clear();error('');await render();if($('#editor').open)editorContent();toast(result.changed?(staticMode?'已载入最新网页快照':'已读取最新 Excel 数据'):'数据已是最新');}catch(e){error(e.message);}finally{refreshing=false;$('#refresh').disabled=false;$('#refresh').textContent=staticMode?'↻ 检查网页更新':'↻ 刷新数据';}}
$('#refresh').onclick=refresh;
function renderSources(){const sources=catalog.sources;$('#sources').innerHTML=`<div class="help" style="margin-bottom:18px">${staticMode?'这里展示发布时的数据快照，可用「检查网页更新」读取新版本。此网页不能访问你电脑上的 Excel；研究页面和图表配置仅保存到当前浏览器。':'直接读取本机 Excel 文件。每 15 秒检查文件变化，保存工作簿后自动更新。公式使用 Excel 已保存的缓存值；无缓存公式保留为空。移除数据源仅移除注册记录，不会删除原 Excel。'}</div>`+(sources.length?sources.map(s=>`<article class="source-panel"><div class="source-heading"><div><h2>${esc(s.name)}</h2><p>${esc(staticMode?String(s.filename||s.path||s.name||'').split(/[\\/]/).at(-1):s.path)}</p></div>${staticMode?'':`<div class="compact-actions"><button data-refresh-source="${esc(s.id)}">刷新此源</button><button data-remove-source="${esc(s.id)}" class="danger">移除注册</button></div>`}</div><div class="source-info"><span class="badge">${esc(statusLabels[s.status]||'待检查')}</span><span>${esc(s.group||'未分组')}</span><span>${s.sheets?.length||0} 张工作表</span><span>更新于 ${esc(dateDisplay(s.updatedAt))}</span></div>${s.error?'<p class="error-banner">'+esc(s.error)+'</p>':''}${(s.sheets||[]).map(sh=>`<details class="sheet"><summary><strong>${esc(sh.name)}</strong><span class="badge">${esc(statusLabels[sh.status]||'待检查')}</span><span class="muted">${sh.rows} 行 × ${sh.columns} 列 · ${sh.indicatorCount} 个指标</span></summary><p class="source-hint">识别布局：${esc(layoutLabels[sh.layout]||'未识别')}<br>${(sh.warnings||[]).map(esc).join('<br>')||'未发现导入警告'}</p><div class="table-wrap"><table><tbody>${(sh.preview||[]).slice(0,10).map((row,r)=>`<tr><th>样本 ${r+1}</th>${row.slice(0,10).map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><details style="margin-top:12px"><summary class="muted">查看指标与 Excel 定位</summary><div class="table-wrap"><table><thead><tr><th>指标</th><th>单位</th><th>Excel 定位</th><th>有效观测</th></tr></thead><tbody>${catalog.indicators.filter(i=>i.sourceId===s.id&&i.sheet===sh.name).slice(0,300).map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.unit||'未注明')}</td><td>${esc(i.locator)}</td><td>${i.count} 条 · ${esc(i.start)} 至 ${esc(i.end)}</td></tr>`).join('')||'<tr><td colspan="4">此工作表无已识别时序指标，保留原始检查记录。</td></tr>'}</tbody></table></div></details></details>`).join('')}</article>`).join(''):`<div class="empty card">${staticMode?'当前网页快照未发布数据源。':'尚未接入数据源。点击右上角「添加数据源」。'}</div>`);
 $('#sources').querySelectorAll('[data-refresh-source]').forEach(el=>el.onclick=async()=>{el.disabled=true;el.textContent='正在读取…';try{const result=await api('refresh','POST',{sourceId:el.dataset.refreshSource});setCatalog(result.catalog);values.clear();error('');render();toast('数据源已刷新');}catch(e){error(e.message);el.disabled=false;el.textContent='刷新此源';}});
 $('#sources').querySelectorAll('[data-remove-source]').forEach(el=>el.onclick=()=>{const s=sources.find(s=>s.id===el.dataset.removeSource);confirmAction('移除数据源注册',`移除「${s.name}」的注册与缓存。不会删除或修改原 Excel 文件。使用此源的图表将提示指标失效。`,async()=>{const result=await api('sources/'+encodeURIComponent(s.id),'DELETE');setCatalog(result.catalog);values.clear();render();toast('已移除注册，原 Excel 保留');});});}
function addSource(){if(staticMode){toast('网页快照不能读取本地 Excel，请使用发布后的数据。');return;}modal('添加本地 Excel 数据源',`<form id="source-form"><p class="help">输入完整文件路径。工作簿保留在原位置，本工作台只读访问。</p><label class="field">Excel 文件完整路径<input name="path" placeholder="E:\\研究数据\\工作簿.xlsx" required autofocus></label><label class="field">显示名称（可选）<input name="name" placeholder="例如：集成电路进出口"></label><label class="field">分组（可选）<input name="group" placeholder="例如：产业与贸易"></label><p id="source-error" class="status-error" role="alert"></p><div class="dialog-actions"><button type="button" data-cancel>取消</button><button class="primary" type="submit">读取并接入</button></div></form>`,()=>{$('[data-cancel]').onclick=()=>$('#modal').close();$('#source-form').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('[type=submit]');button.disabled=true;button.textContent='正在检查工作表…';try{const data=Object.fromEntries(new FormData(form));data.path=data.path.trim().replace(/^"|"$/g,'');const result=await api('sources','POST',data);setCatalog(result.catalog);values.clear();addSourcePage(result.sourceId);$('#modal').close();view='sources';render();toast('数据源已接入，研究页面已创建');}catch(ex){$('#source-error').textContent=ex.message;button.disabled=false;button.textContent='读取并接入';}};});}
function addSourcePage(sourceId){const source=catalog.sources.find(s=>s.id===sourceId);if(!source)return;const hierarchies=(catalog.hierarchies||[]).filter(h=>h.sourceId===sourceId);if(hierarchies.length){for(const h of hierarchies){let p=workspace.pages.find(p=>p.hierarchy?.id===h.id||p.hierarchyId===h.id);if(!p){const title=workspace.pages.some(p=>p.name===h.name)?h.name+' · '+source.name:h.name;p={id:uid(),name:title,cards:[],hierarchy:{id:h.id,sourceId:h.sourceId,rootCode:h.rootCode}};workspace.pages.push(p);}}save();return;}const sourceItems=catalog.indicators.filter(i=>i.sourceId===sourceId&&i.count>0),raw=sourceItems.filter(i=>!i.percent),items=(raw.length?raw:sourceItems).slice(0,2);if(!items.length)return;const name=source.group||source.name;let page=workspace.pages.find(p=>p.name===name);if(!page){page={id:uid(),name,cards:[]};workspace.pages.push(page);}page.cards.push(card(source.name+' · 走势','line',items.map(i=>i.id)),card(source.name+' · 五年季节性','seasonal',[items[0].id]));save();}
async function syncExternalPages(){
 if(staticMode||!externalSourceIds.size)return false;
 // Capture external additions before an already queued local save can replace them.
 const before=await api('workspace');
 let result=mergeSourcePages(workspace,before,externalSourceIds,catalog.indicators),changed=result.changed;
 const found=new Set(result.found);
 clearTimeout(saveTimer);flushSave();await saveChain;
 const after=await api('workspace');
 result=mergeSourcePages(workspace,after,externalSourceIds,catalog.indicators);changed=changed||result.changed;
 for(const id of result.found)found.add(id);
 for(const id of found)externalSourceIds.delete(id);
 if(changed){save();clearTimeout(saveTimer);flushSave();await saveChain;}
 return changed;
}
async function poll(){if(refreshing||polling||document.hidden)return;polling=true;try{
 const next=await api('catalog');$('#connection').textContent=connectionMessage;
 const known=new Set(catalog.sources.map(s=>s.id));
 if(!staticMode)for(const source of next.sources)if(!known.has(source.id))externalSourceIds.add(source.id);
 const dataChanged=next.version!==catalog.version;
 if(dataChanged){setCatalog(next);values.clear();}
 const pagesChanged=await syncExternalPages();
 if(dataChanged||pagesChanged){await render();if($('#editor').open){renderSelected();renderIndicators();}toast(pagesChanged?'已同步新增数据源的研究页面':'检测到数据更新，图表已刷新');}
 }catch(e){$('#connection').textContent=staticMode?'网页更新检查失败 · 自动重试':'连接中断 · 自动重试';}finally{polling=false;}}

async function init(){try{const [data,saved]=await Promise.all([api('catalog'),api('workspace')]);setCatalog(data);workspace=saved?.pages?.length?saved:defaults();if(!workspace.pages.some(p=>p.id===workspace.activePageId))workspace.activePageId=workspace.pages[0].id;$('#save-status').textContent=staticMode?'配置已载入':savedMessage;await render();if(staticApi?.storageWarning())error(staticApi.storageWarning());if(!saved)save();setInterval(poll,15000);}catch(e){error(e.message+(staticMode?' 请检查网络连接后刷新页面。':' 请确认本地服务正在运行，然后刷新页面。'));$('#save-status').textContent='未连接';$('#connection').textContent=staticMode?'网页快照暂不可用':'本地服务不可用';}}
if(staticMode){document.title='研数 · 宏观研究看板';$('#environment-label').textContent='公开网页快照';$('#environment-note').textContent='DIY 配置仅保存到此浏览器';$('#footer-label').textContent='研数 · 宏观研究看板 · 网页快照';$('#sources-nav').querySelector('span').textContent='数据来源';$('#refresh').textContent='↻ 检查网页更新';$('#page-meta').textContent='正在读取已发布数据…';}
init();
