import {esc,formatNumber,renderChart} from './charts.js';

const fieldLabels={raw:'当月原值',yoy:'当月同比',mom:'当月环比',ytd:'年内累计值',ytd_yoy:'累计同比'};
const flowLabels={export:'出口',import:'进口'};
const metricLabels={amount:'金额',quantity:'数量'};
const percentageFields=new Set(['yoy','mom','ytd_yoy']);
const number=value=>typeof value==='number'&&Number.isFinite(value);
function concise(value,percent=false){if(!number(value))return'—';if(percent)return formatNumber(value,true);if(Math.abs(value)>=1e8)return formatNumber(value/1e8)+'亿';if(Math.abs(value)>=1e4)return formatNumber(value/1e4)+'万';return formatNumber(value);}
function unique(items){return[...new Set(items.filter(Boolean))];}

/** Select a legacy page only when both its topic and its source are unambiguous. */
export function matchPageHierarchy(page,catalog){
 const list=catalog.hierarchies||[];
 if(!page.hierarchy&&page.hierarchyId)return list.find(h=>h.id===page.hierarchyId)||null;
 if(page.hierarchy?.id)return list.find(h=>h.id===page.hierarchy.id&&h.sourceId===page.hierarchy.sourceId)||null;
 const code=page.name==='集成电路'?'8542':['自动设备','自动数据处理设备'].includes(page.name)?'8471':null;
 if(!code)return null;
 const indicatorSources=new Map(catalog.indicators.map(i=>[i.id,i.sourceId]));
 const sources=new Set(page.cards.flatMap(c=>c.series.map(s=>indicatorSources.get(s.indicatorId))).filter(Boolean));
 const matches=list.filter(h=>h.rootCode===code&&sources.has(h.sourceId));
 return matches.length===1?matches[0]:null;
}

export function visibleHierarchyNodes(nodes,collapsed,query=''){
 const byCode=new Map(nodes.map(n=>[n.code,n])),matching=new Set(),q=query.trim().toLowerCase();
 if(q)for(const node of nodes)if((node.name+' '+node.code).toLowerCase().includes(q)){let current=node;const seen=new Set();while(current&&!seen.has(current.code)){seen.add(current.code);matching.add(current.code);current=byCode.get(current.parentCode);}}
 return nodes.filter(node=>{if(q)return matching.has(node.code);let parent=byCode.get(node.parentCode);const seen=new Set();while(parent&&!seen.has(parent.code)){if(collapsed.has(parent.code))return false;seen.add(parent.code);parent=byCode.get(parent.parentCode);}return true;});
}

export function createHierarchyUI({element,getCatalog,getPage,getMeta,getValues,api,ensureValues,makeCard,onSave,onAddCard,toast}){
 let epoch=0,previewEpoch=0,payload=null,query='',trendFields={amount:'raw',quantity:'raw'},lastPageId=null;
 const cache=new Map();
 const el=()=>document.querySelector(element);
 function save(){onSave();}
 function resolve(){const page=getPage(),catalog=getCatalog(),h=matchPageHierarchy(page,catalog);if(h&&!page.hierarchy){page.hierarchy={id:h.id,sourceId:h.sourceId,rootCode:h.rootCode,hidden:false,flow:'export',metric:'amount',month:'latest',selectedCode:h.rootCode,collapsed:[]};const level6=h.nodes.filter(n=>n.level===6);page.hierarchy.collapsed=level6.slice(1).map(n=>n.code);page.hierarchy.selectedCode=level6[0]?.code||h.rootCode;page.hierarchyId=h.id;save();}if(h&&page.hierarchy){const defaults={hidden:false,flow:'export',metric:'amount',month:'latest',selectedCode:h.rootCode,collapsed:[]};for(const [key,value]of Object.entries(defaults))if(page.hierarchy[key]===undefined||page.hierarchy[key]===null)page.hierarchy[key]=value;}if(h&&page.hierarchy&&!page.hierarchy.diyInitialized){
   if(!page.cards.length){const direction=page.hierarchy.flow||'export';const initial=h.nodes.find(n=>n.code===page.hierarchy.selectedCode&&n.series?.[direction]?.amount?.raw)||h.nodes.find(n=>n.level===6&&n.series?.[direction]?.amount?.raw)||h.nodes.find(n=>n.series?.[direction]?.amount?.raw);if(initial){const amountId=initial.series[direction].amount.raw,quantityId=initial.series[direction].quantity?.raw;page.cards.push(makeCard(`${initial.name}（${initial.code}）· ${flowLabels[direction]}金额`,'line',[amountId]),quantityId?makeCard(`${initial.name}（${initial.code}）· ${flowLabels[direction]}数量`,'line',[quantityId]):makeCard(`${initial.name}（${initial.code}）· ${flowLabels[direction]}金额季节性`,'seasonal',[amountId]));}}
   page.hierarchy.diyInitialized=true;save();
  }return{page,h,state:page.hierarchy};}
 function chartCard(node,metric,field){const state=getPage().hierarchy,id=node.series?.[metric]?.[field];const c=makeCard(`${node.name}（${node.code}）· ${flowLabels[state.flow]}${metricLabels[metric]} · ${fieldLabels[field]}`,'line',id?[id]:[]);c.id='hierarchy-preview-'+metric;if(/^\d{4}-\d{2}$/.test(state.month||'')){const [year,month]=state.month.split('-').map(Number);c.end=new Date(Date.UTC(year,month,0)).toISOString().slice(0,10);}return c;}
 function metricsMarkup(node,metric){const m=node.metrics?.[metric]||{},field=trendFields[metric];return `<div class="product-metric-block"><div class="product-metric-heading"><strong>${flowLabels[getPage().hierarchy.flow]}${metricLabels[metric]}</strong><span title="${esc(typeof m.coverage==='string'?m.coverage:'')}">${esc(m.unit||'原表未注明单位')}</span></div><div class="product-metric-grid">${Object.entries(fieldLabels).map(([key,label])=>{const value=key==='raw'?m.value:m[key],id=node.series?.[metric]?.[key];return `<button class="product-metric ${field===key?'active':''}" data-h-metric="${metric}" data-h-field="${key}" ${!id?'disabled':''} title="${esc(label)}：${esc(number(value)?formatNumber(value,percentageFields.has(key)):'无可用观测')}"><span>${label}</span><strong class="${percentageFields.has(key)&&number(value)?value>0?'positive':value<0?'negative':'':''}">${concise(value,percentageFields.has(key))}</strong></button>`;}).join('')}</div></div>`;}
 function selectedNode(){const state=getPage()?.hierarchy;return payload?.nodes?.find(n=>n.code===state?.selectedCode)||payload?.nodes?.find(n=>n.code===payload.rootCode)||payload?.nodes?.[0];}
 function renderSelected(){const target=el().querySelector('[data-h-detail]'),node=selectedNode();if(!target||!node)return;const state=getPage().hierarchy;const warnings=unique([...(node.warnings||[]),...(node.metrics?.amount?.warnings||[]),...(node.metrics?.quantity?.warnings||[])]);target.innerHTML=`<div class="selected-product-header"><div><span class="eyebrow">SELECTED PRODUCT</span><h3>${esc(node.name)} <span class="code-label">${esc(node.code)}</span></h3></div><span class="muted">${esc(payload.date)} · ${flowLabels[state.flow]} · 点击指标切换下方趋势</span></div><div class="product-metrics">${metricsMarkup(node,'amount')}${metricsMarkup(node,'quantity')}</div>${warnings.length?`<details class="hierarchy-detail-warning"><summary>查看该商品口径说明（${warnings.length}）</summary><p>${warnings.map(esc).join('<br>')}</p></details>`:''}<div class="product-preview-grid">${['amount','quantity'].map(metric=>`<article class="product-preview"><div class="product-preview-head"><strong>${metricLabels[metric]} · ${fieldLabels[trendFields[metric]]}</strong><button data-h-add="${metric}" ${!node.series?.[metric]?.[trendFields[metric]]?'disabled':''}>＋ 加入 DIY 图表</button></div><div class="chart" id="hierarchy-chart-${metric}"></div><div class="chart-warning" data-h-chart-warning="${metric}" hidden></div></article>`).join('')}</div><div class="hierarchy-evidence"><details><summary>查看商品关系与来源依据</summary>${(node.evidence||[]).map(e=>`<div>${e.method==='prefix_inference'?'<span class="inferred-badge">编码前缀推导</span>':'<span class="badge">原表明确标注</span>'} ${esc(e.sheet)} · ${esc(e.cell)} <span class="muted">${esc(e.text)}</span></div>`).join('')||'<p class="muted">此节点由后端映射提供，未附单独定位记录。</p>'}</details><span>联动预览不修改已保存的 DIY 图卡。</span></div>`;drawPreviews();}
 async function drawPreviews(){const previewToken=++previewEpoch,token=epoch,node=selectedNode();if(!node)return;const cards=['amount','quantity'].map(metric=>chartCard(node,metric,trendFields[metric]));try{await ensureValues(cards);if(token!==epoch||previewToken!==previewEpoch||selectedNode()?.code!==node.code)return;for(const [i,metric]of ['amount','quantity'].entries()){const target=el().querySelector('#hierarchy-chart-'+metric);if(!target)return;if(!cards[i].series.length){target.innerHTML='<div class="empty">该商品没有此指标的可用映射。</div>';continue;}const warnings=await renderChart(target,cards[i],getMeta(),getValues());const note=el().querySelector('[data-h-chart-warning="'+metric+'"]');if(note){note.hidden=!warnings.length;note.textContent=warnings.join('；');}}}catch(e){if(token!==epoch||previewToken!==previewEpoch)return;for(const target of el().querySelectorAll('.product-preview .chart'))target.innerHTML='<div class="empty">'+esc(e.message)+'</div>';}}
 function renderRows(){const state=getPage().hierarchy,metric=state.metric||'amount',collapsed=new Set(state.collapsed||[]),children=new Set(payload.nodes.map(n=>n.parentCode).filter(Boolean)),nodes=visibleHierarchyNodes(payload.nodes,collapsed,query),body=el().querySelector('[data-h-rows]');if(!body)return;body.innerHTML=nodes.map(node=>{const m=node.metrics?.[metric]||{},inferred=(node.evidence||[]).some(e=>e.method==='prefix_inference'),reason=unique([...(m.warnings||[]),...(node.warnings||[])]).join('；');return `<tr data-h-row="${esc(node.code)}" class="${node.code===state.selectedCode?'selected':''} level-${node.level}"><td class="product-name-cell"><div style="padding-left:${(node.level-4)*10}px">${children.has(node.code)?`<button class="tree-toggle" data-h-toggle="${esc(node.code)}" aria-label="${collapsed.has(node.code)?'展开':'收起'} ${esc(node.name)}" aria-expanded="${!collapsed.has(node.code)}">${collapsed.has(node.code)?'▸':'▾'}</button>`:'<span class="tree-leaf">·</span>'}<button class="product-name" data-h-select="${esc(node.code)}" title="${esc(node.name)}">${esc(node.name)}</button>${inferred?'<span class="inferred-badge" title="原工作簿缺少该层级标签，关系由HS编码前缀推导">推导</span>':''}</div></td><td><span class="hs-level">HS${node.level}</span><span class="hs-code">${esc(node.code)}</span></td><td class="share-cell" title="${esc(number(m.share)?m.shareLabel||'占源覆盖HS4叶子篮子':reason||'份额不可计算')}">${number(m.share)?`<span class="share-track"><span style="width:${Math.max(0,Math.min(100,m.share*100))}%"></span></span><strong>${concise(m.share,true)}</strong>`:'<span class="unavailable-share">— <small>口径不可比或缺失</small></span>'}</td><td title="${esc(number(m.value)?formatNumber(m.value)+' '+(m.unit||'单位未注明'):'无观测')}">${concise(m.value)}<small class="unit-note">${esc(m.unit||'')}</small></td>${['yoy','mom','ytd_yoy'].map(field=>`<td class="${number(m[field])?m[field]>0?'positive':m[field]<0?'negative':'':''}">${concise(m[field],true)}</td>`).join('')}</tr>`;}).join('')||'<tr><td colspan="7" class="empty">没有匹配商品，请调整搜索条件。</td></tr>';el().querySelector('[data-h-count]').textContent=`显示 ${nodes.length} / ${payload.nodes.length} 个节点`;}
 function content(){const {h,state}=resolve(),metric=state.metric||'amount',source=getCatalog().sources.find(s=>s.id===h.sourceId),denominator=payload.denominator||{},den=denominator[metric]||{};const warningText=unique([...(payload.warnings||[]),...(den.warnings||[])]);const allMonths=payload.availableMonths||[];
 el().innerHTML=`<section class="hierarchy-panel"><header class="hierarchy-heading"><div><span class="eyebrow">PRODUCT STRUCTURE</span><h2>商品层级与贸易表现 <span class="badge">HS4 → HS6 → HS8</span></h2><p>${esc(source?.name||'当前数据源')} <span>·</span> ${esc(h.name)} <span>·</span> HS4 ${esc(h.rootCode)}</p></div><button class="text-button" data-h-hide>隐藏商品层级</button></header><div class="hierarchy-controls"><label>贸易方向<select data-h-control="flow"><option value="export" ${state.flow==='export'?'selected':''}>出口</option><option value="import" ${state.flow==='import'?'selected':''}>进口</option></select></label><label>份额与表格指标<select data-h-control="metric"><option value="amount" ${metric==='amount'?'selected':''}>金额</option><option value="quantity" ${metric==='quantity'?'selected':''}>数量</option></select></label><label>观测月份<select data-h-control="month"><option value="latest" ${state.month==='latest'?'selected':''}>最新 · ${esc(allMonths.at(-1)||payload.date)}</option>${allMonths.slice().reverse().map(month=>`<option value="${esc(month)}" ${state.month===month?'selected':''}>${esc(month)}</option>`).join('')}</select></label><label class="hierarchy-search">搜索商品或 HS 编码<input type="search" data-h-search value="${esc(query)}" placeholder="例如：存储器 / 854232"></label><div class="tree-actions"><button data-h-expand>全部展开</button><button data-h-collapse>收起子项</button></div></div><div class="hierarchy-basis"><span class="basis-tag">份额口径</span><span>${esc(denominator.label||'源文件覆盖的 HS8 叶子篮子')} · ${denominator.official?'官方合计':'源表覆盖口径，未验证 HS4 全量'}；所有 HS6 / HS8 均占所属 HS4，非占直接父级。</span><span class="basis-value">${metricLabels[metric]}分母：${concise(den.value)} ${esc(den.unit||'单位未注明')} · ${esc(typeof den.coverage==='string'?den.coverage:'')}</span></div>${warningText.length?`<details class="hierarchy-alert" ${metric==='quantity'?'open':''}><summary>口径与覆盖提示（${warningText.length}）</summary><p>${warningText.map(esc).join('<br>')}</p></details>`:''}<div class="hierarchy-table-wrap"><table class="hierarchy-table"><thead><tr><th>商品名称</th><th>HS 编码</th><th>占 HS4（当月）</th><th>当月${metricLabels[metric]}</th><th>当月同比</th><th>当月环比</th><th>累计同比</th></tr></thead><tbody data-h-rows></tbody></table></div><div class="hierarchy-table-footer"><span data-h-count></span><span>份额仅按所选月计算 · — 表示缺失或口径不可比 · 点击商品联动查看明细</span></div><section class="selected-product" data-h-detail></section></section>`;
 renderRows();renderSelected();bind();}
 function bind(){const host=el();host.onchange=e=>{const key=e.target.dataset.hControl;if(!key)return;const state=getPage().hierarchy;state[key]=e.target.value;save();if(key==='metric'){content();return;}render();};host.oninput=e=>{if(e.target.matches('[data-h-search]')){query=e.target.value;renderRows();}};host.onclick=e=>{const state=getPage().hierarchy;if(e.target.closest('[data-h-hide]')){state.hidden=true;save();render();return;}if(e.target.closest('[data-h-show]')){state.hidden=false;save();render();return;}const toggle=e.target.closest('[data-h-toggle]');if(toggle){state.collapsed=state.collapsed.includes(toggle.dataset.hToggle)?state.collapsed.filter(c=>c!==toggle.dataset.hToggle):[...state.collapsed,toggle.dataset.hToggle];save();renderRows();return;}if(e.target.closest('[data-h-expand]')){state.collapsed=[];save();renderRows();return;}if(e.target.closest('[data-h-collapse]')){state.collapsed=payload.nodes.filter(n=>n.level===6).map(n=>n.code);save();renderRows();return;}const row=e.target.closest('[data-h-row]');if(row){state.selectedCode=row.dataset.hRow;save();renderRows();renderSelected();return;}const metric=e.target.closest('[data-h-metric]');if(metric){trendFields[metric.dataset.hMetric]=metric.dataset.hField;renderSelected();return;}const add=e.target.closest('[data-h-add]');if(add){const metric=add.dataset.hAdd,node=selectedNode(),c=chartCard(node,metric,trendFields[metric]);c.id=crypto.randomUUID();onAddCard(c);toast('已加入下方 DIY 图表，可独立编辑');}};}
 async function render(){const token=++epoch,host=el();if(!host)return;const {page,h,state}=resolve();if(lastPageId!==page.id){query='';trendFields={amount:'raw',quantity:'raw'};lastPageId=page.id;}host.hidden=!h&&!state;if(!h){host.innerHTML=state?'<div class="hierarchy-unavailable">当前页面绑定的商品层级已不可用，请检查数据源状态。原 DIY 图表保留。</div>':'';return;}host.hidden=false;if(state.hidden){host.innerHTML=`<div class="hierarchy-hidden"><span>商品层级已隐藏 · ${esc(h.name)} / HS4 ${esc(h.rootCode)}</span><button data-h-show>显示商品层级</button></div>`;bind();return;}host.innerHTML='<div class="hierarchy-panel hierarchy-loading">正在读取商品层级与当月贸易指标…</div>';const key=[getCatalog().version,h.id,state.flow,state.month].join('|');try{let result=cache.get(key);if(!result){result=await api('hierarchy?id='+encodeURIComponent(h.id)+'&flow='+encodeURIComponent(state.flow||'export')+'&date='+encodeURIComponent(state.month||'latest'));cache.set(key,result);if(cache.size>30)cache.delete(cache.keys().next().value);}if(token!==epoch||getPage().id!==page.id)return;payload=result;if(!payload.nodes.some(n=>n.code===state.selectedCode)){state.selectedCode=payload.rootCode;save();}content();}catch(e){if(token===epoch)host.innerHTML='<div class="hierarchy-unavailable">商品层级暂未读取成功：'+esc(e.message)+'。下方 DIY 图表仍可使用。</div>';}}
 function hide(){epoch++;const host=el();if(host)host.hidden=true;}
 return{render,hide};
}
